name: 'Link Availability Validator'
description: 'Validate that links in your repo are up and available'

inputs:
  args:
    description: 'Arguments to urlsup'
    required: true

runs:
  using: 'docker'
  image: 'docker://simeg/urlsup:2.0.0'
  args:
    - ${{ inputs.args }}

branding:
  icon: check-circle
  color: green
